### ISSUE TITLE
Code Runner missing the PHP extension

### ISSUE THREAD

**Issue by David-Arcos-369** [bradtraversy/php-crash#1]
Hey Brad,
Installed everything following your great tutorial,  but the .run  was not recognizing PHP  what a nightmare. Installed the extensions  you suggested got the live server going but, VS would not start the server it kept on giving PHP not found message, even tho I cloned your crash course and the live server will show the entire file structure  in port 5500.

**Comment by Boinero** [comment]
https://www.youtube.com/watch?v=begPcGfAwzY

Try watching this tutorial to see if it helps for Windows users.

**Comment by nikhilmahajan918** [comment]
Hey David, If you have set up PHP using XAMPP, then you have to really only care about the PATH variable. Follow this youtube video "https://www.youtube.com/watch?v=NAvMN2tqBZM&ab_channel=NickFrostbutter" for reference.

**Comment by David-Arcos-369** [comment]
> Hey David, If you have set up PHP using XAMPP, then you have to really only care about the PATH variable. Follow this youtube video "https://www.youtube.com/watch?v=NAvMN2tqBZM&ab_channel=NickFrostbutter" for reference.

Thanks for reaching out!  I moved on, probably go back and try to finish the project, it was just giving me errors in the console so I couldn't move forward, I think I have extensions conflicts in VSCode
